name = "bqsh"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

kv_namespaces = [
  { binding = "FEISHU_KV", id = "576f4e274ed64404a9519cce09f764dc" }
]

[vars]
FEISHU_MULTI_TENANT = "true"
FEISHU_SYNC_PAGE_SIZE = "4000"
FEISHU_WRITE_BATCH_SIZE = "100"
FEISHU_QPS_LIMIT = "10"
